# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class login_MainWindow(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(499, 400)
        self.u_name_label = QtWidgets.QLabel(Dialog)
        self.u_name_label.setGeometry(QtCore.QRect(120, 150, 120, 40))
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold Condensed")
        self.u_name_label.setFont(font)
        self.u_name_label.setObjectName("u_name_label")
        self.pass_label = QtWidgets.QLabel(Dialog)
        self.pass_label.setGeometry(QtCore.QRect(120, 180, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold Condensed")
        self.pass_label.setFont(font)
        self.pass_label.setObjectName("pass_label")
        self.log_Button = QtWidgets.QPushButton(Dialog)
        self.log_Button.setGeometry(QtCore.QRect(160, 230, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold Condensed")
        self.log_Button.setFont(font)
        self.log_Button.setObjectName("log_Button")
        self.sign_up_Button = QtWidgets.QPushButton(Dialog)
        self.sign_up_Button.setGeometry(QtCore.QRect(270, 230, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold Condensed")
        self.sign_up_Button.setFont(font)
        self.sign_up_Button.setObjectName("sign_up_Button")
        self.u_name_line = QtWidgets.QLineEdit(Dialog)
        self.u_name_line.setGeometry(QtCore.QRect(250, 160, 113, 22))
        self.u_name_line.setObjectName("u_name_line")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(170, 70, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold Condensed")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pass_line = QtWidgets.QLineEdit(Dialog)
        self.pass_line.setGeometry(QtCore.QRect(250, 190, 113, 22))
        self.pass_line.setObjectName("pass_line")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.u_name_label.setText(_translate("Dialog", "Kullanıcı adı"))
        self.pass_label.setText(_translate("Dialog", "Sifre"))
        self.log_Button.setText(_translate("Dialog", "Giriş Yap"))
        self.sign_up_Button.setText(_translate("Dialog", "Kayıt Ol"))
        self.label.setText(_translate("Dialog", "GIRIS YAP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = login_MainWindow()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
